#!/usr/bin/env python3
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

de = os.environ.get("XDG_CURRENT_DESKTOP", "").lower()

if "gnome" in de:
    from ui_gtk.main import run
else:
    # KDE, COSMIC, anything else → Qt
    from ui_qt.main import run

run()