#!/usr/bin/env bash
set -e

echo "Setting up virtualization for RakuOS..."

sudo rakuos install \
    libvirt-daemon-config-network \
    libvirt-daemon-kvm \
    qemu-kvm \
    virt-manager

# After installing virt packages copy polkit rules to /etc so they persist
cp /usr/share/polkit-1/actions/org.libvirt.*.policy /etc/polkit-1/actions/

echo "Enabling libvirt service..."
sudo systemctl enable --now libvirtd

echo ""
echo "Virtualization packages layered."
echo "Please reboot to use libvirt and virt-manager."