#!/bin/bash
set -e

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root: sudo rakuos stoat"
  exit 1
fi

STOAT_VERSION="1.3.0"
STOAT_ZIP="Stoat-linux-x64-${STOAT_VERSION}.zip"
STOAT_URL="https://github.com/stoatchat/for-desktop/releases/download/v${STOAT_VERSION}/${STOAT_ZIP}"

INSTALL_DIR="/opt/Stoat-linux-x64"
BIN_LINK="/usr/local/bin/stoat"
DESKTOP_FILE="/usr/local/share/applications/stoat.desktop"
ICON_PATH="/usr/local/share/icons/stoat.png"

OPT_ZIP="/opt/${STOAT_ZIP}"

# Download directly to /opt
echo "Downloading Stoat ${STOAT_VERSION}..."
wget "$STOAT_URL" -O "$OPT_ZIP"

echo "Installing Stoat..."

rm -rf "$INSTALL_DIR"
unzip -o "$OPT_ZIP" -d /opt

# Delete zip immediately after extraction
rm -f "$OPT_ZIP"
echo "Cleaned up zip."

if [ ! -f "$INSTALL_DIR/stoat-desktop" ]; then
    echo "ERROR: stoat-desktop not found after extraction"
    exit 1
fi

chmod 755 "$INSTALL_DIR"
chmod -R a+rX "$INSTALL_DIR"
chmod a+x "$INSTALL_DIR/stoat-desktop"

ln -sf "$INSTALL_DIR/stoat-desktop" "$BIN_LINK"

# Icon
mkdir -p "$(dirname "$ICON_PATH")"
wget -q https://raw.githubusercontent.com/stoatchat/assets/refs/heads/main/desktop/icon.png -O "$ICON_PATH"

# Desktop entry
mkdir -p "$(dirname "$DESKTOP_FILE")"
cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Name=Stoat
Comment=Stoat Chat Client
Exec=$BIN_LINK
Icon=stoat
Terminal=false
Type=Application
Categories=Network;Chat;
StartupWMClass=Stoat
EOF

echo "Stoat ${STOAT_VERSION} installation complete!"