#!/bin/bash

set -ouex pipefail

# Determine the installed kernel version
QUALIFIED_KERNEL=$(rpm -q --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}\n' kernel-cachyos)

# Snapshot installed packages before nvidia install so we can capture the full
# dep tree that dnf pulls in (explicit installs + all pulled-in deps).
# post-build.sh will check for this file and append the base package list to it.
rpm -qa --qf '%{NAME}\n' | sort > /tmp/pre-nvidia-pkgs.txt

# Install NVIDIA stack — skip systemd scriptlets that fail in containers
dnf5 install -y --setopt=tsflags=noscripts \
    dkms-nvidia \
    nvidia-driver \
    nvidia-persistenced

# Diff pre/post — write directly to protected-packages.txt so post-build.sh
# knows this is a nvidia build and appends the base list to it.
mkdir -p /usr/share/rakuos
{
    echo "# NVIDIA packages and all dependencies (generated by nvidia.sh)"
    rpm -qa --qf '%{NAME}\n' | sort | comm -13 /tmp/pre-nvidia-pkgs.txt -
} > /usr/share/rakuos/protected-packages.txt
rm -f /tmp/pre-nvidia-pkgs.txt
echo "Recorded $(wc -l < /usr/share/rakuos/protected-packages.txt) nvidia packages for protection."

# Build DKMS module for the installed kernel
# Force ld.bfd — gold linker fails with NVIDIA's -r + --gc-sections combination
NVIDIA_VER=$(rpm -q --queryformat '%{VERSION}\n' dkms-nvidia)
LD=ld.bfd dkms install -m nvidia -v "${NVIDIA_VER}" -k "${QUALIFIED_KERNEL}" --force || {
    echo "DKMS build failed — make.log:"
    cat /var/lib/dkms/nvidia/${NVIDIA_VER}/build/make.log || true
    exit 1
}

# Enable NVIDIA power management services
systemctl enable nvidia-powerd.service \
    nvidia-persistenced.service

# Generate module dependencies
depmod "${QUALIFIED_KERNEL}"

# Generate initramfs with nvidia module included
/usr/bin/dracut --no-hostonly --kver "${QUALIFIED_KERNEL}" --reproducible --zstd -v \
    --add ostree --add fido2 -f "/usr/lib/modules/${QUALIFIED_KERNEL}/initramfs.img"

chmod 0600 /usr/lib/modules/"${QUALIFIED_KERNEL}"/initramfs.img
