# RakuOS Flatpak command overrides
# Format: <FlatpakID>=<command>

org.mozilla.firefox=firefox
org.mozilla.Thunderbird=thunderbird
org.libreoffice.LibreOffice=libreoffice
com.visualstudio.code=code
com.valvesoftware.Steam=steam
io.mpv.Mpv=mpv
org.videolan.VLC=vlc
org.gimp.GIMP=gimp
com.discordapp.Discord=discord